---

# Make sure that these paths are correct
circomPath: "./node_modules/circom/cli.js"
snarkjsPath: "./node_modules/snarkjs/build/cli.cjs"
circomRuntimePath: "./node_modules/circom_runtime"
ffiasmPath: "./node_modules/ffiasm"

out: "./zkeys"

circuits:
- template: "./circom/hasher.circom"
  component: "Hasher"
  params: [2]
  type: "test"

- template: "./circom/hasher.circom"
  component: "Hasher"
  params: [3]
  type: "prod"

ptauFiles:
  1:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAAYj0ZxlbebJCf3E1PBRoNua/powersOfTau28_hez_final_01.ptau?dl=1"
      name: "powersOfTau28_hez_final_01.ptau"

  2:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAAeQw8hH4IIuzP_rLpz66RYa/powersOfTau28_hez_final_02.ptau?dl=1"
      name: "powersOfTau28_hez_final_02.ptau"

  3:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAD0NrEyUDt0XcdjSFCUuE3va/powersOfTau28_hez_final_03.ptau?dl=0"
      name: "powersOfTau28_hez_final_03.ptau"

  4:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAC4WyolU3e_x9LxE2aFd3kia/powersOfTau28_hez_final_04.ptau?dl=0"
      name: "powersOfTau28_hez_final_04.ptau"

  5:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAC6OSGf-hblPfTHvBs_lC2xa/powersOfTau28_hez_final_05.ptau?dl=1"
      name: "powersOfTau28_hez_final_05.ptau"

  6:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAAmaQMo4WQiRfvhUiYTZQDUa/powersOfTau28_hez_final_06.ptau?dl=1"
      name: "powersOfTau28_hez_final_06.ptau"

  7:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AADYuEY5ILETNZrgeRbxi2yOa/powersOfTau28_hez_final_07.ptau?dl=1"
      name: "powersOfTau28_hez_final_7:.ptau"

  8:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAB4qkL78dCpFg3U8RVMV84ta/powersOfTau28_hez_final_08.ptau?dl=1"
      name: "powersOfTau28_hez_final_8:.ptau"

  9:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAAZL94PkM2zKFudvc4xTPCxa/powersOfTau28_hez_final_09.ptau?dl=1"
      name: "powersOfTau28_hez_final_9:.ptau"

  10:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AABJqL_Nj1ETJztaNDDTmrLDa/powersOfTau28_hez_final_10.ptau?dl=1"
      name: "powersOfTau28_hez_final_10.ptau"

  11:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AADzwfVSajP0WMKs8PwWSKA1a/powersOfTau28_hez_final_11.ptau?dl=1"
      name: "powersOfTau28_hez_final_11.ptau"

  12:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAAfGzkJYERPx9HYuD7cCsEEa/powersOfTau28_hez_final_12.ptau?dl=1"
      name: "powersOfTau28_hez_final_12.ptau"

  13:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AABu_KJP0VLNWrSm2uJV6AtZa/powersOfTau28_hez_final_13.ptau?dl=1"
      name: "powersOfTau28_hez_final_13.ptau"

  14:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AABjB4hJNSPWxtJiXXvn7D0va/powersOfTau28_hez_final_14.ptau?dl=1"
      name: "powersOfTau28_hez_final_14.ptau"

  15:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AABUJYyC5CYI5YZgj1GdDFDka/powersOfTau28_hez_final_15.ptau?dl=1"
      name: "powersOfTau28_hez_final_15.ptau"

  16:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAAI-XPJ7jKfw6FfZzqhiFspa/powersOfTau28_hez_final_16.ptau?dl=1"
      name: "powersOfTau28_hez_final_16.ptau"

  17:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AACFE-eD4MW90b7xbiE6PQVVa/powersOfTau28_hez_final_17.ptau?dl=1"
      name: "powersOfTau28_hez_final_17.ptau"

  18:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAD2MuF2ngVpTO5f5R-8t4pMa/powersOfTau28_hez_final_18.ptau?dl=1"
      name: "powersOfTau28_hez_final_18.ptau"

  19:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AACvwhMYBxrhhgNiZWSbtV2ca/powersOfTau28_hez_final_19.ptau?dl=1"
      name: "powersOfTau28_hez_final_19.ptau"

  20:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAAPqwIbgTbBchVJog8XIifBa/powersOfTau28_hez_final_20.ptau?dl=1"
      name: "powersOfTau28_hez_final_20.ptau"

  21:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AABiMm_4UMnvU0VIkCDVX9XZa/powersOfTau28_hez_final_21.ptau?dl=1"
      name: "powersOfTau28_hez_final_21.ptau"

  22:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAAzGtg94saShf044uZdwnuGa/powersOfTau28_hez_final_22.ptau?dl=1"
      name: "powersOfTau28_hez_final_22.ptau"

  23:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AACXdEyzF6V5G5SLwlcV24pYa/powersOfTau28_hez_final_23.ptau?dl=1"
      name: "powersOfTau28_hez_final_23.ptau"

  24:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AAAi2DHbiB5LhGGFRJ_M2DwVa/powersOfTau28_hez_final_24.ptau?dl=1"
      name: "powersOfTau28_hez_final_24.ptau"

  25:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AABtJqpgsk93Xe-gtLauqycTa/powersOfTau28_hez_final_25.ptau?dl=1"
      name: "powersOfTau28_hez_final_25.ptau"

  26:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AABcvvD2qA2wGwJCU2AhbwX0a/powersOfTau28_hez_final_26.ptau?dl=1"
      name: "powersOfTau28_hez_final_26.ptau"

  27:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AACxvAidsajKkHS5eMgpnHyZa/powersOfTau28_hez_final_27.ptau?dl=1"
      name: "powersOfTau28_hez_final_27.ptau"

  28:
      url: "https://www.dropbox.com/sh/mn47gnepqu88mzl/AADgFSy_UnsSoDwOPy64tpCWa/powersOfTau28_hez_final.ptau?dl=1"
      name: "powersOfTau28_hez_final_28.ptau"
